from datetime import datetime, timezone, timedelta

def estimate_niftybees(gift_nifty_price, divisor):
    return round(gift_nifty_price / divisor, 2)

def get_market_mood(change_pct):
    if change_pct <= -3: return "🔴🔴🔴 CRASH MODE"
    elif change_pct <= -1.5: return "🔴🔴 BIG DIP"
    elif change_pct <= -0.5: return "🔴 MILD DIP"
    elif change_pct <= 0.5: return "🟡 FLAT"
    elif change_pct <= 1.5: return "🟢 POSITIVE"
    else: return "🟢🟢 STRONG RALLY"

def analyze_gtt(estimated_bees, gtt):
    if gtt["status"] != "active":
        return {"name": gtt["name"], "verdict": "ALREADY TRIGGERED ✅", "action": "Done", "gap": 0}

    gap = round(estimated_bees - gtt["trigger"], 2)

    if estimated_bees <= gtt["trigger"]:
        verdict, action = "🔥 WILL TRIGGER AT OPEN!", "DO NOT MODIFY"
    elif gap <= 3:
        verdict, action = "⚠️ VERY CLOSE", "DO NOT MODIFY"
    elif gap <= 7:
        verdict, action = "🟡 POSSIBLE if market dips", "Keep as-is"
    elif gap > 15:
        verdict, action = "💤 Far away", "Consider lowering"
    else:
        verdict, action = "💤 Unlikely today", "Keep as-is"

    return {"name": gtt["name"], "trigger": gtt["trigger"], "verdict": verdict, "action": action, "gap": gap}

def generate_message(gift_nifty, config):
    divisor = config["nifty_to_bees_divisor"]
    prev_close = config["nifty_prev_close"]
    bees_prev = config["niftybees_prev_close"]

    estimated_bees = estimate_niftybees(gift_nifty, divisor)
    change_pct = round((gift_nifty - prev_close) / prev_close * 100, 2)
    bees_change = round(estimated_bees - bees_prev, 2)
    mood = get_market_mood(change_pct)

    ist = timezone(timedelta(hours=5, minutes=30))
    now_ist = datetime.now(ist).strftime("%d-%b %I:%M %p IST")

    msg = (
        f"📊 GIFT NIFTY MONITOR\n"
        f"⏰ {now_ist}\n\n"
        f"GIFT Nifty: {gift_nifty:,.0f} ({change_pct:+.2f}%)\n"
        f"Mood: {mood}\n\n"
        f"Expected NIFTYBEES: ~Rs.{estimated_bees}\n"
        f"Change: Rs.{bees_change:+.2f}\n\n"
        f"--- YOUR GTTs ---\n"
    )

    any_action = False
    for gtt in config["gtts"]:
        r = analyze_gtt(estimated_bees, gtt)
        if gtt["status"] != "active":
            msg += f"\n{r['name']}: {r['verdict']}\n"
        else:
            msg += f"\n{r['name']} | Trigger Rs.{r['trigger']}\nGap: Rs.{r['gap']:.1f} | {r['verdict']}\nAction: {r['action']}\n"
            if "Consider" in r["action"]:
                any_action = True

    msg += "\n--- ADVICE ---\n"
    if any_action:
        msg += "⚠️ Some GTTs far from market. Consider adjusting.\n"
    else:
        msg += "✅ All GTTs look good. No changes needed.\n"

    msg += "\n-- Auto-generated by GIFT Nifty Agent --"
    return msg
